### ISSUE TITLE
Simple Ceylon app

### ISSUE THREAD

**Issue by minkir014** [jvasileff/vscode-ceylon#14]
I have a simple project which when I open autocompletion not working although it didn't show errors about java, Ceylon or dart

**Comment by jvasileff** [comment]
Thanks for your interest, but this project isn’t being actively developed (you can see from the commit log) and I don’t have time to provide support for it right now. This is likely to change if development activity on Ceylon picks back up.

So, I’m going to go ahead and close this issue.
