### ISSUE TITLE
List LSP support on LSP page

### ISSUE THREAD

**Issue by mickaelistria** [jvasileff/vscode-ceylon#8]
The reference page for listing languages supported LSP is https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations , please make sure the Ceylon support from https://github.com/jvasileff/vscode-ceylon/blob/master/server/source/com/vasileff/ceylon/vscode/module.ceylon is added there ( request to https://github.com/Microsoft/vscode-languageserver-protocol/issues/8 )

**Comment by jvasileff** [comment]
@mickaelistria good idea, thanks. I've posted the request.

**Comment by jvasileff** [comment]
Done!
